#! /bin/sh

# roughly maps onto the check_rom script in the original Android Kitchen, which
# validates an input ROM and sets up a working directory. Some of the check_rom
# functionality was separated into other scripts. That will be done with both
# scripts and functions here.

EXTRACT_ROM_TITLE="CREATE WORKING FOLDER FOR ROM"
EXTRACT_ROM_MESSAGE="Ensure there is at least one ROM under the \"$SCULLERY_ROM_DIR\" folder!

Select an option:
"
EXTRACT_OR_SHOW=0
MAKE_BACKUP_ROM="Do you want to back up your existing working folder for your ROM?
"

ROM_FORMATS_MESSAGE=$(cat "$SCULLERY_FUNCTIONS_DIR/formats.txt")

extract_or_show(){
    EXTRACT_OR_SHOW=$(dialog --title "$EXTRACT_ROM_TITLE" --menu "$EXTRACT_ROM_MESSAGE" 14 60 2 \
        1 "Show supported formats:" \
        2 "Continue to ROM select menu" \
        3>&1 1>&2 2>&3 3>&- )
}

make_backup_working(){
    MAKE_BACKUP=$(dialog --title "$EXTRACT_ROM_TITLE" --yesno "$MAKE_BACKUP_ROM" 14 80 \
            3>&1 1>&2 2>&3 3>&-)    
    if [ "$MAKE_BACKUP" = "yes" ]; then
	FILE_PASSED="$1"
        WORKING_FOLDER=filename="${FILE_PASSED##*/}"
        do_backup "$WORKING_FOLDER"
    fi
}

actually_extract(){
    ROM_ZIP="$1"
    make_backup_working "$ROM_ZIP"
    do_unzip "$ROM_ZIP"
}

loopover(){
    if [ $EXTRACT_OR_SHOW = 0 ]; then
        extract_or_show
    elif [ $EXTRACT_OR_SHOW = 1 ]; then
        dialog --title "$EXTRACT_ROM_TITLE" --msgbox "$ROM_FORMATS_MESSAGE" 14 80
    elif [ $EXTRACT_OR_SHOW = 2 ]; then
        ROMS_AVAILABLE=checkout_romdir
        WHICH_ROM=$(dialog --title "$EXTRACT_ROM_TITLE" --menu "$EXTRACT_ROM_FROM_AVAIL" 14 80 2 \
            "$ROMS_AVAILABLE" \
            3>&1 1>&2 2>&3 3>&-)
        actually_extract "$WHICH_ROM"
    fi
}

run_extract_rom(){
    ROM_FILE="$1"
    if [ ! -f "$ROM_FILE" ]; then
        while [ $EXTRACT_OR_SHOW = 0 ]; do
            loopover
        done
        loopover
        echo $ROMS_AVAILABLE
    else
        actually_extract "$ROM_FILE"
    fi
}
